server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        # 换成nginx的1111端口，做集群
        server-addr: 192.168.66.66:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"